### PR TITLE
Update kube-rs to 0.57 and k8s-openapi to 0.12

### PR DESCRIPTION
**Pull request by lfrancke**
This has some breaking changes for downstream users but will allow us to treat Crds generic

https://github.com/clux/kube-rs/blob/master/CHANGELOG.md
https://github.com/Arnavion/k8s-openapi/blob/master/CHANGELOG.md

### CODE REVIEW

**Review by maltesander — DISMISSED** [review]
Looks good!

**Comment by lfrancke** [comment]
Thanks. Do you think we should merge it now?
It'll probably require changes in all operators.

**Comment by maltesander** [comment]
Yes maybe we wait until we have the other bigger changes merged from product config etc.

**Review by maltesander — APPROVED** [review]
LGTM

**Pull request merged**
