### PR TITLE
[Merged by Bors] - Expose memory quantity parser directly

### PR DESCRIPTION
**Pull request by teozkr**
## Description

This is used by https://github.com/stackabletech/nifi-operator/pull/371.

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM. This is non breaking due to `Memory` not being public right?

**Comment by teozkr** [comment]
Yes.

**Comment by maltesander** [comment]
Go for it!

**Review by sbernauer — APPROVED** [review]
Nice thanks!

**Pull request closed without merging**
