### PR TITLE
[Merged by Bors] - Use ephemeral secret-op volumes rather than csi

### PR DESCRIPTION
**Pull request by teozkr**
## Description

Requires https://github.com/stackabletech/secret-operator/pull/125, see that PR for motivation

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM. 
Edit: Is `Ephemeral(Box<EphemeralVolumeSource>)` in the enum really required? I mean we do not store 1000s of elements of that in a list. Whats against `#[allow(clippy::enum_large_variants)]` (not sure thats exactly how the lint is called)?

**Comment by teozkr** [comment]
Yeah the main problem with `enum_large_variants` is that it inflates the size of that type regardless of which variant we use. If we don't particularly are about that then we can just use use it inline.

**Comment by maltesander** [comment]
> Yeah the main problem with `enum_large_variants` is that it inflates the size of that type regardless of which variant we use, which might also make things like moves slower depending on the ABI that the compiler ends up deciding on. If we don't particularly are about that then we can just use use it inline.

Yeah but we do not really move that around or store a lot of elements in a list or sth. I think we can ignore the memory overhead for one item here?

**Review by sbernauer — APPROVED** [review]

**Pull request closed without merging**
