### PR TITLE
[Merged by Bors] - Add pathStyleAccess to S3ConnectionSpec

### PR DESCRIPTION
**Pull request by siegfriedweber**
## Description

`pathStyleAccess` added to `commons::s3::S3ConnectionSpec`

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Comment by sbernauer** [comment]
I think the main question is: What is the default value? ;)
Pros of default to true:
* It should work anywhere (vs. lots of users having problems and need to figure out their S3 doesn't support host style access)
Pros of default to false:
* Maybe better performance for AWS S3? Or lower costs from AWS S3?

So i guess we should default to true for maximum portability

**Comment by sbernauer** [comment]
And i still can't get around that the bool is optional and not just simply defaulting to true (or false).
But i guess that's the way it is :D

**Comment by maltesander** [comment]
> I think the main question is: What is the default value? ;) Pros of default to true:
> 
> * It should work anywhere (vs. lots of users having problems and need to figure out their S3 doesn't support host style access)
>   Pros of default to false:
> * Maybe better performance for AWS S3? Or lower costs from AWS S3?
> 
> So i guess we should default to true for maximum portability

I think pathstyle access will be deprecated at some point? Not sure for every provider, at least for AWS. So for now i would default to true, but still use it in every example and set it explicitly.

**Comment by sbernauer** [comment]
Sounds good :+1: 
The Option actually is really bad IMHO here as we cannot simply set the default to true but instead every individual operator has to enforce the default by itself. Is there any chance of using a bool and default to true?

**Comment by maltesander** [comment]
> Sounds good +1 The Option actually is really bad IMHO here as we cannot simply set the default to true but instead every individual operator has to enforce the default by itself. Is there any chance of using a bool and default to true?

I think it makes sense that each operator does it on its own. When setting that you can just have an unwrap_or() with the default best suited for the operator.

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by maltesander** [comment]
bors merge

**Review by sbernauer — APPROVED** [review]

**Comment by sbernauer** [comment]
bors cancel

**Comment by maltesander** [comment]
bors merge

**Comment by maltesander** [comment]
bors merge

**Pull request closed without merging**
