### PR TITLE
[Merged by Bors] - Removed affinity property that was added by accitdent

### PR DESCRIPTION
**Pull request by fhennig**
## Description

I wanted to add the affinity functions to the PodBuilder, not the RoleGroup. Oops.

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM.

**Comment by fhennig** [comment]
bors merge

**Comment by fhennig** [comment]
bors merge

**Comment by fhennig** [comment]
bors cancel

**Comment by fhennig** [comment]
bors merge

**Pull request closed without merging**
