### PR TITLE
[Merged by Bors] - Set fields to None instead of Some(empty map)

### PR DESCRIPTION
**Pull request by razvan**

### CODE REVIEW

**Comment by teozkr** [comment]
What's the rationale here?

**Comment by razvan** [comment]
Consistency I guess. If the operator defaults for these fields are None, this method will turn them into Some().

**Comment by soenkeliebau** [comment]
ping @teozkr: are you happy with the reasoning here?

**Review by teozkr — APPROVED** [review]
Sorry, forgot about this PR.

I don't think it really matters since K8s should just deep-merge the requests objects anyway, but semantically I think this makes sense to say.

**Comment by razvan** [comment]
bors merge

**Comment by razvan** [comment]
bors merge

**Pull request closed without merging**
