### PR TITLE
PodBuilder can now set pod affinity

### PR DESCRIPTION
**Pull request by andlaz**
## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by lfrancke** [comment]
Thank you very much for your contribution! I've just kicked off a CI run.

**Comment by teozkr** [comment]
The changes look good to me, thanks! I'd be happy to merge this once the CI errors are sorted out.

**Comment by andlaz** [comment]
thanks! Please let me know if this looks good enough, it may get uglier down the line when anti-affinity is added

**Comment by lfrancke** [comment]
Hi @andlaz, unfortunately there are still some clippy & rustfmt issues.
Would you mind updating the PR?

**Comment by andlaz** [comment]
yes, thanks, let me have a quick look

**Comment by lfrancke** [comment]
Thank you, there's only one rustfmt issue left :)
Almost there!

**Comment by maltesander** [comment]
Thank you @andlaz, ill go ahead and merge

**Comment by maltesander** [comment]
bors merge

**Pull request merged**
