### PR TITLE
chore: Add crate release helper scripts

### PR DESCRIPTION
**Pull request by NickLarsenNZ**
# Description

Added script to help with release crates:
- `.scripts/verify_crate_versions.sh` - used to ensure `CHANGELOG.md` versions match what is in `Cargo.toml`. Useful when creating a release PR.
- `.scripts/tag_and_push_release.sh` - used after a release PR has been merged. It will fetch the origin, and tag each _not yet tagged_ release to the selected commit, and optionally push the tags.

> [!TIP]
> Should we add `.scripts/verify_crate_versions.sh` to the pre-commit hooks? This can save a lot of time and human error.

### CODE REVIEW

**Comment by NickLarsenNZ** [comment]
> Do we maybe want to add `shellcheck` to the reviewdog workflow to make sure these scripts are valid?

Oh good point. I ran shellcheck across them first, so never realised it wasn't already a check.

Let me add it in this PR.

**Comment by Techassi** [comment]
I'm also in favour of adding the `.scripts/verify_crate_versions.sh` script to the pre-commit config.

**Comment by NickLarsenNZ** [comment]
I've added shellcheck to both reviewdog and pre-commit (copied from the docker-images repo), and added the verify_crate_versions.sh to the pre-commit config.

I have not added a pre-commit github action, so CI will not pickup mismatched versions (between Cargo.toml and CHANGELOG.md).

Would you like me to add [that workflow](https://github.com/stackabletech/docker-images/blob/main/.github/workflows/pr_pre-commit.yaml) in?

**Comment by Techassi** [comment]
> Would you like me to add [that workflow](https://github.com/stackabletech/docker-images/blob/main/.github/workflows/pr_pre-commit.yaml?rgh-link-date=2024-07-10T13%3A32%3A13Z) in?

Tbh, I would keep it as is for now. I would rather invest more time in better tooling / improving the workflows (in the future).

**Comment by NickLarsenNZ** [comment]
> Tbh, I would keep it as is for now. I would rather invest more time in better tooling / improving the workflows (in the future).

I more meant pre-commit running in Github Actions (not so much this temporary script). Much is duplicated by review dog (same dilemma in docker-images).

**Review by Techassi — APPROVED** [review]

**Comment by Techassi** [comment]
> > Tbh, I would keep it as is for now. I would rather invest more time in better tooling / improving the workflows (in the future).
> 
> I more meant pre-commit running in Github Actions (not so much this temporary script). Much is duplicated by review dog (same dilemma in docker-images).

Sure, let's add it. Shouldn't be much work anyway. We should keep in mind that much of that work will eventually be replaced (for example when moving this repo to it's own org).

**Comment by NickLarsenNZ** [comment]
> Sure, let's add it. Shouldn't be much work anyway. We should keep in mind that much of that work will eventually be replaced (for example when moving this repo to it's own org).

Do you mean either reviewdog or pre-commit wouldn't be used anymore? At least the functionality those two provide will be needed in some capacity.

Side-note: I would be in favour of dropping reviewdog for pre-commit, since the latter can work locally and in CI (maybe reviewdog can too though).

**Review by Techassi — APPROVED** [review]

**Comment by Techassi** [comment]
> Do you mean either reviewdog or pre-commit wouldn't be used anymore? At least the functionality those two provide will be needed in some capacity.

No, they still will be used, but the workflows around it will probably change.

> Side-note: I would be in favour of dropping reviewdog for pre-commit, since the latter can work locally and in CI (maybe reviewdog can too though).

Yeah, interesting idea. Worth exploring in the future.

**Pull request merged**
