### PR TITLE
[Merged by Bors] - Fix clippy 1.67.0 warnings

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

Fix warnings of clippy 1.67.0. We have not bumped yet but I'm fixing them early on
Please review commits individually

## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)
- [x] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
Thanks. LGTM!

**Comment by sbernauer** [comment]
bors cancel

**Comment by sbernauer** [comment]
Missing a release note entry as we change public API, don't we? :thinking: 
Need to check if this is a breaking change in our operators

**Comment by sbernauer** [comment]
Did a short test in kafka-op, everything worked fine. I don't think we changed our public api

**Pull request closed without merging**
