### PR TITLE
[Merged by Bors] - Add support for secret-operator volumes to pod volume builder

### PR DESCRIPTION
**Pull request by teozkr**
## Review Checklist
- [x] Code contains useful comments
- [x] (Integration-)Test cases added (or not applicable)
- [x] Documentation added (or not applicable)
- [x] Changelog updated (or not applicable)

### CODE REVIEW

**Comment by sbernauer** [comment]
Thanks a lot!
In the AuthenticationClass we get a user-provided scope from the user (see below). My understanding is, that the attribute `spec.protocol.ldap.bindCredentials.scope` is a string and is just passed to the Pod volume, is that correct?
In that case we would need a way to just pass in the `secrets.stackable.tech/scope` string and skip creating Rust vectors.

```
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: myldap
spec:
  protocol:
    ldap:
      hostname: ldap.server
      port: 389
      domain: domain.local
      bindCredentials:
        secretClass: superset-with-ldap-ldap-bind
        scope: Service
```

**Comment by teozkr** [comment]
> My understanding is, that the attribute spec.protocol.ldap.bindCredentials.scope is a string and is just passed to the Pod volume, is that correct?

Sort of.. the question there would be how much we want to validate in the operator vs just passing it through. We might also want to force certain scopes when we know that a service will require them.. not sure there.

**Comment by sbernauer** [comment]
Alright, i will think of a solution

**Comment by sbernauer** [comment]
I will also add some unit test as I'm working on new features for `SecretOperatorVolumeSourceBuilder`.
So I'm going to check that in the Review Checklist

**Review by sbernauer — APPROVED** [review]

**Comment by teozkr** [comment]
Kinda getting mixed signals here... :P

**Comment by sbernauer** [comment]
I'm happy to merge this as is. I'm working on the "passing a scope string to SecretOperatorVolumeSourceBuilder" but will open a separate PR for that.

**Comment by teozkr** [comment]
Alright.

bors r+

**Pull request closed without merging**
