### PR TITLE
refactor: Switch from snafu to thiserror

### PR DESCRIPTION
**Pull request by sbernauer**
As discussed in Architecture meeting

# Description

*Please add a description here. This will become the commit message of the merge request later.*

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [x] Changes are OpenShift compatible
- [x] CRD changes approved
- [x] Integration tests passed (for non trivial changes)
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
```

### CODE REVIEW

**Comment by lfrancke** [comment]
I usually keep out of these discussions but in the past we switched from thiserror to snafu. Why switch back now?

**Comment by Techassi** [comment]
Both have their strengths and weaknesses. I will invest some (private) time to maybe come up with a solutions which combines the strengths of both these libraries.

**Comment by sbernauer** [comment]
I have no opinion on the tooling, I just touched error handling code in a different PR and wanted to unify.
We have a decision in the Arch meeting agenda, line 300:


> Context; We use both snafu and thiserror in our code.
> Question: Should we consolidate this and in that case, should we use snafu or thiserror?
> Suggestion: IDK, as I don't know them well enough

> Furter context:
> https://github.com/stackabletech/operator-rs/pull/632#discussion_r1285491225
> https://github.com/kube-rs/kube/discussions/453 might be interesting"

with the outcome
> We prefer thiserror and migrate Error enums when we touch them (e.g. add a new variant) or need it for other reasons (e.g. nice log output in cockpit). Sascha will created a trackig issue, see https://github.com/stackabletech/issues/issues/421

I mean we can have this discussion again. Maybe we need a ADR this time to have everyone involved and formally approving it...

**Comment by lfrancke** [comment]
No no, I'm fine with the decision. It's yours to make not mine.
I just wanted to make sure. I don't want to switch back in a year :)

**Comment by sbernauer** [comment]
I as well! :D
Will make a final call in Slack to have everyone on board

**Comment by sbernauer** [comment]
Closing this, as we agreed upon snafu

**Pull request closed without merging**
