### PR TITLE
[Merged by Bors] - Change credentials of S3ConnectionSpec to use the common SecretClassVolume struct

### PR DESCRIPTION
**Pull request by sbernauer**
## Description

As discussed today

## Review Checklist
- [ ] Code contains useful comments
- [ ] (Integration-)Test cases added (or not applicable)
- [ ] Documentation added (or not applicable)
- [ ] Changelog updated (or not applicable)
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)

Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

### CODE REVIEW

**Review by maltesander — APPROVED** [review]
LGTM!

**Comment by sbernauer** [comment]
If it's okay for you i would merge it tomorrow to let people have the time to have an objection?

**Comment by sbernauer** [comment]
bors retry

**Comment by sbernauer** [comment]
bors cancel

**Pull request closed without merging**
